openapi: 3.0.0
info:
  title: Notification Service API
  description: API for managing and sending notifications.
  version: "1.0"
servers:
  - url: 'http://api.transpacksys.com/notification-service'
paths:
  /notifications:
    post:
      summary: Send a notification
      operationId: sendNotification
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationRequest'
      responses:
        '202':
          description: Notification accepted for delivery
        '400':
          description: Bad request

components:
  schemas:
    NotificationRequest:
      type: object
      required:
        - userId
        - message
      properties:
        userId:
          type: string
        message:
          type: string
