openapi: 3.0.0
info:
  title: Package Tracking Service API
  description: API for tracking packages.
  version: "1.0"
servers:
  - url: "http://api.transpacksys.com/package-tracking"
paths:
  /packages/{trackingId}:
    get:
      summary: Get package by Tracking ID
      operationId: getPackageByTrackingId
      tags:
        - Tracking
      parameters:
        - name: trackingId
          in: path
          required: true
          description: Unique tracking ID of the package
          schema:
            type: string
      responses:
        "200":
          description: Package tracking details
        "404":
          description: Package not found
