apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: user-management
  projectName: TransPackSys
  annotations:
    componentType: service
spec:
  inbound:
    - name: user-management
      port: 3000
      type: REST
      visibility: Project
      context: .
      schemaFilePath: openapi.yaml
  outbound:
      serviceReferences:
      - name: choreo:///kanushkagayan/lpar/btpmlu/40c92b81-2ddd-4933-9422-a920b7e27736/v1.0/inventory/public
        dependentConfig: config-1
        connectionType: service
