apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: user-management
  projectName: TransPackSys
  annotations:
    componentType: service
spec:
  inbound:
    - name: user-management
      port: 3001
      type: REST
      visibility: Project
      context: .
      schemaFilePath: openapi.yaml
  outbound:
      serviceReferences:

