apiVersion: core.choreo.dev/v1alpha1
kind: ComponentConfig
metadata:
  name: payment-processing
  projectName: TransPackSys
  annotations:
    componentType: service
spec:
  inbound:
    - name: payment-processing
      port: 3000
      type: REST
      visibility: Project
      context: .
      schemaFilePath: openapi.yaml
