openapi: 3.0.0
info:
  title: Payment Processing Service API
  description: API for processing payments for package delivery.
  version: "1.0"
servers:
  - url: 'http://api.transpacksys.com/payment-processing'
paths:
  /payments:
    post:
      summary: Process a payment for a delivery
      operationId: processPayment
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentDetails'
      responses:
        '201':
          description: Payment processed
        '400':
          description: Payment failed

components:
  schemas:
    PaymentDetails:
      type: object
      required:
        - userId
        - amount
      properties:
        userId:
          type: string
        amount:
          type: number
          format: double
