openapi: 3.0.0
info:
  title: User Management Service API
  description: API for managing user accounts and profiles.
  version: "1.0"
servers:
  - url: "http://api.transpacksys.com/user-management"
paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewUser"
      responses:
        "201":
          description: User created
        "400":
          description: Bad request

  /users/{userId}:
    get:
      summary: Get user by ID
      operationId: getUserById
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          description: Unique ID of the user
          schema:
            type: string
      responses:
        "200":
          description: User details
        "404":
          description: User not found

components:
  schemas:
    NewUser:
      type: object
      required:
        - username
        - password
        - email
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
